### PR TITLE
#27 immediate "lazy" evaluation to avoid dispose issues

### PR DESCRIPTION
**Pull request by DGuidi**
Probably the best code is to remove Lazy objects at all: I don't want to change too much code, but if you wish...   
I needed to "fix" also two tests that explicitely asserts that an exception is thrown if a disposed object was used to read for data.

### CODE REVIEW

**Review by airbreather — COMMENTED** [review]
> Probably the best code is to remove Lazy objects at all: I don't want to change too much code, but if you wish...

I agree that we should remove the Lazy objects entirely.  There's nothing "lazy" about what we're doing anymore, and it's a much better-looking result even though it touches slightly more code.

Otherwise, this looks good enough to me.

**Review by airbreather — APPROVED** [review]

**Comment by DGuidi** [comment]
actually remove lazy objects required not so much code changes

**Comment by DGuidi** [comment]
Feel free to merge the PR, or let me know if I must do the merge by myself.

**Comment by DGuidi** [comment]
as a side note, to attribute similar to `GeoJsonIssueNumber` - see [this comment](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/pull/47#discussion_r370114443) -  exists here

**Comment by airbreather** [comment]
> as a side note, to attribute similar to `GeoJsonIssueNumber` - see [this comment](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/pull/47#discussion_r370114443) - exists here

9345ebe

**Pull request merged**
